# Generated by Django 4.0.5 on 2023-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receiverId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='senderId',
            field=models.IntegerField(default=0),
        ),
    ]
