# Generated by Django 4.2 on 2023-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_receiverid_chat_senderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receiverId',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='chat',
            name='senderId',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
